geekshop/adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UserListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.CategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.CategoryListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', adminapp.CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/update/<int:pk>/', adminapp.ProductEditView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
]

geekshop/authapp/urls.py
from . import views
from django.urls import path, re_path

app_name = 'authapp'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    re_path(
        r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$',
        views.verify,
        name='verify'
    ),
]

geekshop/basketapp/urls.py
from . import views
from django.urls import path

app_name = 'basketapp'

urlpatterns = [
    path('', views.view, name='view'),
    path('add/<int:product_id>/', views.add, name='add'),
    path('remove/<int:basket_item_id>/', views.remove, name='remove'),
    path('edit/<int:basket_item_id>/<int:quantity>/', views.edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from mainapp import views as mainapp

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('', mainapp.index, name='main'),
    path('contact/', mainapp.contact, name='contact'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from . import views
from django.urls import path

app_name = 'mainapp'

urlpatterns = [
    path('', views.products, name='all'),
    path('<int:category_id>', views.category, name='category'),
    path('<int:category_id>/<int:page>', views.category, name='paged_category'),
    path('product/<int:product_id>', views.product, name='product'),
]

geekshop/ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import path

app_name = "ordersapp"

urlpatterns = [
    path('', ordersapp.OrderList.as_view(), name='orders_list'),
    path('forming/complete/<int:pk>',
         ordersapp.order_forming_complete, name='order_forming_complete'),
    path('create/', ordersapp.OrderCreate.as_view(),
         name='order_create'),
    path('read/<int:pk>', ordersapp.OrderDetail.as_view(),
         name='order_read'),
    path('update/<int:pk>', ordersapp.OrderUpdate.as_view(),
         name='order_update'),
    path('delete/<int:pk>', ordersapp.OrderDelete.as_view(),
         name='order_delete'),
]

geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    objects = models.Manager()
    name = models.CharField(
        verbose_name='имя',
        max_length=100
    )
    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )

    def __str__(self):
        return self.name


class Product(models.Model):
    objects = models.Manager()
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.CASCADE,
    )
    name = models.CharField(
        verbose_name='имя',
        max_length=100,
    )
    price = models.DecimalField(
        verbose_name='цена',
        decimal_places=2,
        max_digits=7,
    )
    color = models.PositiveIntegerField(
        verbose_name='цвет',
        default=0x000000,
    )
    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )
    image = models.ImageField(
        verbose_name='картинка',
        blank=True,
        upload_to='products',
    )
    quantity = models.PositiveIntegerField(
        verbose_name='количество',
        default=0,
    )

    def __str__(self):
        return self.name

geekshop/mainapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, ProductCategory
from django.core.paginator import Paginator, EmptyPage
import random


def index(request):
    products = Product.objects.all()[:4]

    return render(request, 'mainapp/index.html', context={
        'title': 'Главная',
        'products': products,
    })

def get_hot_product(queryset):
    return random.choice(queryset)


def products(request):
    # with open('products.json', 'r', encoding='UTF-8') as file:
    #     products = json.load(file)
    products = Product.objects.all()
    categories = ProductCategory.objects.all()
    hot_product = get_hot_product(products)
    return render(request, 'mainapp/products.html', context={
        'title': 'Продукты',
        'hot_product': hot_product,
        'products': products.exclude(pk=hot_product.pk)[:4],
        'categories': categories
    })


def category(request, category_id, page=1):
    categories = ProductCategory.objects.all()
    category = get_object_or_404(ProductCategory, id=category_id)
    products = Product.objects.filter(category=category)
    hot_product = get_hot_product(products)

    paginator = Paginator(products.exclude(pk=hot_product.pk), 3)
    try:
        products_page = paginator.page(page)
    except EmptyPage:
        products_page = paginator.page(paginator.num_pages)

    return render(request, 'mainapp/products.html', context={
        'title': 'Продукты',
        'hot_product': get_hot_product(products),
        'paginator': paginator,
        'page': products_page,
        'products': products_page,
        'category': category,
        'categories': categories
    })


def product(request, product_id):
    categories = ProductCategory.objects.all()
    product = get_object_or_404(Product, pk=product_id)
    return render(request, 'mainapp/product.html', context={
        'title': 'Продукты',
        'product': product,
        'categories': categories
    })


def contact(request):
    return render(request, 'mainapp/contact.html', context={
        'title': 'Контакты',
    })

geekshop/mainapp/templates/mainapp/includes/inc_categories_menu.html
<div class="links clearfix">
    <ul class="links-menu">
        <li><a href="{% url 'products:all' %}" class="
            {% if request.resolver_match.view_name == 'products:all' %}active{% endif %}"
        >Все</a></li>
        {% for category in categories %}
        <li><a href="{% url 'products:category' category.id %}" class="
            {% if request.resolver_match.view_name == 'products:category' and request.resolver_match.kwargs.category_id == category.id %}active{% endif %}"
        >{{ category.name }}</a></li>
        {% endfor %}
    </ul>
</div>

geekshop/mainapp/templates/mainapp/includes/inc_main_menu.html
<a href={% url 'main' %} class="logo"></a>
<ul class="menu">
    {% for link in menu_links %}
    <li>
        <a href={% url link.url %}
           {% if request.resolver_match.view_name in link.active %}
           class="active"
           {% endif %}>
            {{ link.name }}
        </a>
    </li>
    {% endfor%}
    {% if user.is_authenticated %}
    <li>
        <div class="dropdown">
            <a class="dropdown-toggle" href="" data-toggle="dropdown">
                <i class="fa fa-user fa-1x"></i>
                {{ user.first_name|default:'Пользователь' }}
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                <li class="dropdown-item">
                    <a href="{% url 'auth:edit' %}">
                        профиль
                    </a>
                </li>
                <li class="dropdown-item">
                    <a href="{% url 'ordersapp:orders_list' %}">
                        заказы
                    </a>
                </li>
            </ul>
        </div>
    </li>
    {% endif %}
    {% if user.is_superuser %}
    <li>
        <a href="{% url 'admin:users' %}">
            Админка
        </a>
    </li>
    {% endif %}
    {% if user.is_authenticated %}
    <li>
        <a href="{% url 'basket:view' %}">
            {% if user.basket.count %} ( {{ user.basket.count }} | {{ user.basket.total_cost }} руб. ) {% endif %}
        </a>
    </li>
    {% endif %}
    <li>
        {% if user.is_authenticated %}
        <a href="{% url 'auth:logout' %}">выйти</a>
        {% else %}
        <a href="{% url 'auth:login' %}">войти</a>
        {% endif %}
    </li>

</ul>
<a href="#" class="search"></a>

geekshop/mainapp/templates/mainapp/includes/inc_products.html
{% if paginator %}
    {% if page.has_previous %}
<a href="{% url 'products:paged_category' category.id page.previous_page_number %}"> Назад </a>
    {% endif %}
    Страница {{ page.number }} из {{ paginator.num_pages }}
    {% if page.has_next %}
<a href="{% url 'products:paged_category' category.id page.next_page_number %}"> Вперед </a>
    {% endif %}

{% endif %}

{% for product in products %}
<div class="block">
    <a href="{% url 'products:product' product.id %}"><img src="/media/{{ product.image }}" alt="">
        <div class="text">
            <img src="/static/css/img/icon-hover.png" alt="img">
            <h4>{{ product.name }}</h4>
            <p>{{ product.description }}</p>
        </div>
    </a>
</div>
{% endfor %}